# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                 # plugin type (gateway, interface, protocol, system, web)
    description:                  # Alternative: description in multiple languages
        de: 'Amazon Dashbutton plugin, **seit SmartHomeNG v1.3**'
        en: ''
    maintainer: pfischi
    tester: psilo909
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/1005266-plugin-amazon-dashbutton

    version: 1.3.0.3               # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: Dashbutton          # class containing the plugin

parameters: NONE
    # Definition of parameters to be configured in etc/plugin.yaml
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
logic_parameters:
    # Definition of logic parameters defined by this plugin

plugin_functions:
    # Definition of function interface of the plugin

