# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: web                      # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung des Pushbullet Service'
        en: ''
    maintainer: '? (lbernau)'
    tester: onkelandy, psilo909, Sandman60
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.5.2                 # Plugin version
    sh_minversion: 1.5             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: Pushbullet          # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    apikey:
        type: str
        mandatory: False
        description:
            de: '(optional) Persönlicher API Key für Pushbullet. Registrierung siehe https://docs.pushbullet.com/. Wenn der Key nicht gesetzt ist, muss er expizit in Funktionsaufrufen gesetzt werden.'
            en: '(optional) Your own personal API key for Pushbullet. For your own key refer to https://docs.pushbullet.com/. If key is not set, you have to use it in function calls.'

    deviceid:
        type: str
        mandatory: False
        description:
            de: '(optional) Id des anzusprechenden Geräts, wo eine Pushbullet App läuft. Auf http://www.pushbullet.com einloggen, Gerät auswählen und den Teil der URL kopieren, der hinter "device_iden=" kommt. Falls nicht gesetzt, muss der Wert explizit in Funktionsaufrufen als Parameter angegeben werden.'
            en: '(optional) Id of referenced device, where Pushbullet app is running. Log in into http://www.pushbullet.com, select target device, copy the part of the browser URL behind "device_iden=" If not set, you have to use it in function calls.'

item_attributes:
    # Definition of item attributes defined by this plugin
